blog/urls.py
from django.contrib import admin
from django.urls import path

import blog.views

urlpatterns = [
    # path('', blog.views.index, name='blog-index'),
    path('', blog.views.BlogListView.as_view(), name='blog-index'),
    path('about/', blog.views.about, name='blog-about'),
    # path('<int:id>', blog.views.detail, name='detail'),
    path('blog/<int:pk>', blog.views.BlogDetailView.as_view(), name='blog-detail'),
    path('blog/new/', blog.views.BlogCreateView.as_view(), name='blog-create'),
    path('blog/<int:pk>/update', blog.views.BlogUpdateView.as_view(), name='blog-update'),
    path('blog/<int:pk>/delete', blog.views.BlogDeleteView.as_view(), name='blog-delete'),
    path('blog/<int:pk>/comment', blog.views.BlogFormView.as_view(), name='blog-form-comment'),
]

practice_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from users import views as user_views
from django.contrib.auth import views as auth_views

import blog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name="main.html"), name='home'),
    path('board/', include('blog.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),

]

blog/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models
from django.urls import reverse
# Create your models here.


class Blog(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    updated = models.DateTimeField(default=timezone.now)
    blog_user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog-detail', kwargs={'pk': self.pk})


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    # comment_title = models.CharField(max_length=200)
    comment_text = models.TextField()
    comment_updated = models.DateTimeField(default=timezone.now)
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.comment_title

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_text']

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User

        fields = ['username', 'email', 'password1', 'password2']

blog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, FormView, ListView
from django.core.paginator import Paginator

# Create your views here.
from django.views.generic.edit import FormMixin, DeleteView

import blog.models
from blog.forms import CommentForm
from blog.models import Blog


# def index(request):
#     # context = {'blogs': blogs}
#     # return render(request, 'blog/index.html', context)
#     try:
#         blogs = Blog.objects.all()
#     except Blog.DoesNotExist:
#         raise Http404("Blog does not exist")
#     return render(request, 'blog/index.html', {'blogs': blogs})


def about(request):
    return render(request, 'blog/about.html')


# def detail(request, id):
#     blog = Blog.objects.get(id=id)
#     context = {'blog': blog}
#     return render(request, 'blog/detail.html', context)


class BlogListView(ListView):
    model = Blog
    paginate_by = 6
    ordering = ['-updated']
    # return object name : object_list


class BlogDetailView(DetailView):
    model = Blog
    # 디테일뷰에서 오브젝트를 가져와서 리턴하는 내용 설명


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ['title', 'content']
    template_name = 'blog/blog_create_form.html'

    def form_valid(self, form):
        # *** from 인스턴스 blog_user를 요청 유저로 저장해야 함 ***
        form.instance.blog_user = self.request.user
        return super().form_valid(form)


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ['title', 'content']
    template_name = 'blog/blog_update_form.html'

    def form_valid(self, form):
        # 권한 검증
        user = self.request.user
        form_blog = Blog.objects.get(pk=self.kwargs.get("pk"))

        if user == form_blog.blog_user:
            return super().form_valid(form)
        else:
            return HttpResponse("<h3>You dont have a permission</h3>")


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog-index')

    def form_valid(self, form):
        # 권한 검증
        user = self.request.user
        form_blog = Blog.objects.get(pk=self.kwargs.get("pk"))
        if user == form_blog.blog_user:
            return super().form_valid(form)
        else:
            return HttpResponse("<h3>You dont have a permission</h3>")


class BlogFormView(LoginRequiredMixin, FormView):
    template_name = 'blog/blog_comment.html'
    form_class = CommentForm

    def get_success_url(self):
        return reverse('blog-detail', kwargs={'pk': self.kwargs.get("pk")})

    def form_valid(self, form):
        form.instance.blog = Blog.objects.get(pk=self.kwargs.get("pk"))
        # comment user를 설정해야 함 ***
        form.instance.comment_user = self.request.user
        form.save()
        return super().form_valid(form)

users/views.py
from django.contrib import messages
from django.shortcuts import render, redirect

# Create your views here.
from users.forms import UserRegisterForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account create for {username}')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous"></script>

    <title>Skeleton</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark">
        <div class="container-sm">
            <a class="navbar-brand" href="{% url 'home' %}">Vacuum skeleton</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
                    aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>

            </button>
            <div class="collapse navbar-collapse" id="navbarText">
                <ul class="navbar-nav me-auto  mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'blog-about' %}">Skeleton</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'blog-index' %}">게시판</a>
                    </li>

                </ul>
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <span class="nav-link active"> {{ user.username }}님 </span>
                        <a class="nav-link active" href="{% url 'logout' %}">로그아웃</a>
                    {% else %}
                        <a class="nav-link active" href="{% url 'login' %}">로그인</a>
                        <a class="nav-link active" href="{% url 'register' %}">회원가입</a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
<div class="container" style="height: 50px"></div>
</header>
<div class="container-sm">
{% block content %}{% endblock %}
</div>
</body>
</html>

templates/blog/about.html
{% extends "base.html" %}
{% block content %}
    <div class="card" style="width: 24rem;">
  <img src="/static/image/20220306_005114.png" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Vacuum Skeleton</h5>
    <p class="card-text">배큠 데모를 위한 사이트 입니다.</p>
    <a href="{% url 'home' %}" class="btn btn-dark">홈으로</a>
  </div>
</div>
{% endblock %}

templates/blog/blog_comment.html
{% extends "base.html" %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <fieldset>
            <legend class="mb-4 fw-bold">코멘트 쓰기</legend>
            {#            <div class="mb-3">#}
            {#                <label label for="id_comment_title" class="form-label fw-bold">TITLE</label>#}
            {#                <input class="form-control" type="text" name="comment_title" maxlength="200" required#}
            {#                       id="id_comment_title">#}
            {#            </div>#}

            <div class="mb-3">
                <label label for="id_comment_text" class="form-label fw-bold">CONTENT</label>
                <textarea class="form-control" type="text" name="comment_text" maxlength="200" required
                          id="id_comment_text"
                          style="height: 300px"></textarea>
            </div>

            <input class="btn btn-dark" type="submit" value="코멘트 작성">
        </fieldset>
    </form>
{% endblock content %}

templates/blog/blog_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-2">
            <p class="fs-4">"{{ object }}" 해당 글을 삭제 합니다. </p>
        </div>

        <input class="btn btn-dark" type="submit" value="Confirm">
    </form>
{% endblock %}

templates/blog/blog_create_form.html
{% extends "base.html" %}
{% block content %}
    <div class="mb-3">
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend class="mb-4 fw-bold">글쓰기</legend>
                <div class="mb-3">
                    <label label for="id_title" class="form-label fw-bold">TITLE</label>
                    <input class="form-control mb-4" type="text" name="title" maxlength="200" required id="id_title"
                           placeholder="Please enter your details.">

                </div>

                <div class="mb-3">
                    <label label for="id_content" class="form-label fw-bold">CONTENT</label>

                    <textarea rows=5 type="text" class="form-control mb-4" name="content"
                              placeholder="Please enter your details." required_id="id_text"
                              style="height: 300px"></textarea>
                </div>

            </fieldset>
            <div>
                <button class="btn btn-dark" type="submit">글쓰기</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/blog/blog_detail.html
{% extends "base.html" %}
{% block content %}


    <div class="card p-2 mb-3">
        <ul><p class="fs-4">{{ blog.title }}</p></ul>
        <ul>
            <small class="font-weight-bold text-primary">{{ blog.blog_user }}</small>
            <small class="font-weight-bold">{{ blog.updated|date:'Y-m-d H:i' }}</small>
        </ul>
    </div>
    <div class="card p-2 mb-4" style="height: 250px">
        <ul><p>{{ blog.content }}</p></ul>
    </div>
    <div>
        <a class="btn btn-dark mb-4" href="{% url 'blog-index' %}" role="button">뒤로가기</a>
        {% if user.is_authenticated %}
            <a class="btn btn-dark mb-4" href="{% url 'blog-form-comment' blog.id %}">코멘트</a>
            {% if blog.blog_user == request.user %}
                <a class="btn btn-dark mb-4" href="{% url 'blog-update' blog.id %}">업데이트</a>
                <a class="btn btn-dark mb-4" href="{% url 'blog-delete' blog.id %}">삭제</a>
            {% endif %}
        {% endif %}
    </div>
    {% if blog.comment_set.all %}
        <div>
            <p class="fs-3">Comments</p>
        </div>
        {% for c in blog.comment_set.all %}
            <div class="card p-3 mb-2">
                <div class="d-flex justify-content-between align-items-center">
                    <div class="user d-flex flex-row align-items-center">
                        <span><small class="font-weight-bold text-primary">{{ c.comment_user }}</small> <small
                                class="font-weight-bold"> {{ c.comment_text }}</small></span></div>
                    <small>{{ c.comment_updated|date:'Y-m-d H:i' }} </small>
                </div>
                {#                <div class="action d-flex justify-content-between mt-2 align-items-center">#}
                {#                    <div class="reply px-4"><small>Remove</small> <span class="dots"></span> <small>Reply</small> <span#}
                {#                            class="dots"></span> <small>Translate</small></div>#}
                {#                    <div class="icons align-items-center"><i class="fa fa-star text-warning"></i> <i#}
                {#                            class="fa fa-check-circle-o check-icon"></i></div>#}
                {#                </div>#}
            </div>
        {% endfor %}
    {% endif %}


{% endblock content %}

templates/blog/blog_list.html
{% extends "base.html" %}
{% block content %}
    {% if object_list %}
        <table class="table table-hover mb-4">
        <thead>
        <tr>
            <th scope="col">제목</th>
            <th scope="col">아이디</th>
            <th scope="col">게시일</th>
        </tr>
        </thead>
        <tbody>

        {% for blog in object_list %}
            <tr>
                <td><a class="text-muted text-decoration-none"
                       href="{% url 'blog-detail' blog.id %}">{{ blog.title }}</a></td>
                <td class="text-decoration-none">{{ blog.blog_user }}</td>
                <td class="text-decoration-none">{{ blog.updated|date:'Y-m-d H:i' }}</td>
            </tr>
        {% endfor %}
    {% else %}
        <p>There's no blog content</p>
    {% endif %}

</tbody>
</table>
    <div class="d-grid gap-2 d-md-flex mb-4">
        <a class="btn btn-dark me-md-2" href="{% url 'blog-create' %}" role="button">글쓰기</a>
    </div>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-1">
                <ul class="pagination">
                    <li class="page-item">
                        {% if page_obj.has_previous %}
                            <a class="page-link text-muted" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                            </a>
                        {% endif %}

                        {% for page in paginator.page_range %}
                            <li class="page-item"><a class="page-link text-muted"
                                                     href="?page={{ page }}">{{ page }}</a></li>
                        {% endfor %}

                    {% if page_obj.has_next %}
                        <a class="page-link text-muted" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>

{% endblock %}

templates/blog/blog_update_form.html
{% extends "base.html" %}
{% block content %}
    <div class="mb-3">
        <form method="POST" >
            {% csrf_token %}
            <fieldset>
                <legend class="mb-4 fw-bold">글쓰기</legend>
                <div class="mb-3">
                    <label label for="id_title" class="form-label fw-bold">TITLE</label>
                    <input class="form-control mb-4" type="text" name="title" maxlength="200" required id="id_title" placeholder="Please enter your details."
                           value="{{ form.title.value }}" >

                </div>

                <div class="mb-3">
                    <label label for="id_content" class="form-label fw-bold">CONTENT</label>

                     <textarea rows=5 type="text" class="form-control mb-4" name="content"
                        placeholder="Please enter your details." required_id="id_text" style="height: 300px">{{ form.content.value }}</textarea>
                </div>

            </fieldset>
            <div>
                <button class="btn btn-dark" type="submit">글쓰기</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/main.html
{% extends "base.html" %}
{% block content %}
    <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="10000">
                <img src="static/image/20220306_005133.png" class="d-block w-40" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>First slide label</h5>
                    <p>Some representative placeholder content for the first slide.</p>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="2000">
                <img src="static/image/20220306_005133.png" class="d-block w-40" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Second slide label</h5>
                    <p>Some representative placeholder content for the second slide.</p>
                </div>
            </div>
            <div class="carousel-item">
                <img src="static/image/20220306_005133.png" class="d-block w-40" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h5>Third slide label</h5>
                    <p>Some representative placeholder content for the third slide.</p>
                </div>
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
{% endblock %}

templates/users/login.html
{% extends "base.html" %}
{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            <div class="mb-3 row">
                <label for="id_username" class="col-sm-2 col-form-label">아이디</label>
                <div class="col-sm-10">
                    <input class="form-control" type="text" name="username" autofocus autocapitalize="none" autocomplete="username"
                           maxlength="150" required id="id_username">
                </div>
            </div>
            <div class="mb-3 row">
                <label for="id_password" class="col-sm-2 col-form-label">패스워드</label>
                <div class="col-sm-10">
                    <input class="form-control" type="password" name="password" autocomplete="current-password" required id="id_password">
                </div>
            </div>
            <div class="col-auto">
                <button type="submit" class="btn btn-dark mb-3">로그인</button>
            </div>


        </form>
    </div>
{% endblock content %}

templates/users/logout.html
{% extends "base.html" %}
{% block content %}
    <h2>You have been logged out</h2>
    <div>
        <small>
            <a href="{% url 'login' %}">Log in again</a>
        </small>
    </div>
{% endblock content %}

templates/users/register.html
{% extends "base.html" %}
{% block content %}
    <div>
        <form method="POST">
            {% csrf_token %}
            <fieldset>
                <legend class="mb-5">회원가입</legend>

                <div class="mb-3 row">
                    <label for="id_username" class="form-label">ID</label>
                    <div class="col-sm-10">
                        <input class="form-control" type="text" name="username" autofocus required id="id_username">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="id_email" class="form-label">Email</label>
                    <div class="col-sm-10">
                        <input type="email" class="form-control" name="email" required id="id_email"
                               placeholder="name@example.com">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="id_password1" class="form-label">Password</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="password1" autocomplete="new-password"
                               required id="id_password1">
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="id_password2" class="form-label">Password check</label>
                    <div class="col-sm-10">
                        <input type="password" class="form-control" name="password2" autocomplete="new-password"
                               required id="id_password2">
                    </div>
                </div>


            </fieldset>
            <div class="col-auto">
                <button type="submit" class="btn btn-dark mb-3">회원가입</button>
            </div>
        </form>
    </div>
    <div>
        <small>
            <p>이미 계정이 있으신가요? <a class="text-muted text-decoration-none" href="/login/"> 로그인</a></p>
        </small>
    </div>
{% endblock content %}